### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Haroenv** [thibmaek/fruity-dashboard#1]
Could be useful as in how to set this up.

**Comment by thibmaek** [comment]
On the list since yesterday :wink: :

![screen shot 2015-05-14 at 10 46 04](https://cloud.githubusercontent.com/assets/6213695/7628674/798f9e56-fa26-11e4-893e-7c79e6d3651c.png)

**Comment by Haroenv** [comment]
Ah, no problem!
